"""Create PCB table

Revision ID: a7863f40891a
Revises: 
Create Date: 2026-08-28 11:09:28.423085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7863f40891a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pcbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_reference', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('equipment', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('pcb_model', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=200), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('failure_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcbs_internal_reference'), 'pcbs', ['internal_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pcbs_internal_reference'), table_name='pcbs')
    op.drop_table('pcbs')
    # ### end Alembic commands ###
